---
# tasks file for roles/apachd

- import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- import_tasks: service-httpd.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- import_tasks: service-apache2.yml
  when: ansible_facts['os_family']|lower == 'debian'

- import_tasks: configure.yml
#- import_tasks: modules.yml
#  when: ansible_facts['os_family']|lower == 'debian'
