---
- name: install packages on Debian/Ubuntu
  apt: name={{ item }} 
     update_cache=yes 
     state=latest
  with_items:
    - git
    - mcrypt
    - nginx
    - php7.4
    - sqlite3
    - php7.4-sqlite3
    - php7.4-fpm
    - php7.4-cli
    - php7.4-curl
    - php7.4-intl
    - php7.4-json

